### PR TITLE
fix(contract): add retry to `waitForTransactionReceipt` (#40)

### LINKED ISSUE #40: Retry `waitForTransactionReceipt` to avoid not-found error caused by load-balanced json rpc server
When using `waitForTransactionReceipt` to wait for a transaction to be mined on a load-balanced JSON-RPC server, sometimes a "block number xxxx is not mined" error is returned even though the transaction has been successfully mined. This is because the JSON-RPC server may return the response from a different node than the one that actually mined the transaction.

To avoid this error, we can add retry logic to `waitForTransactionReceipt`. If the initial request returns a "not-found" error, we can retry the request a few times until the receipt is found.

### PR DESCRIPTION
**Pull request by Songkeys**
fix #40

### CODE REVIEW

**Review by runjuu — APPROVED** [review]
LGTM!

**Review by birdgg — APPROVED** [review]
LGTM

**Comment by Songkeys** [comment]
not LGTM.

It doesn't look like the error has been resolved yet (see the failed CI). Is it possible that the retry times (5) is not enough?

I noticed that the upstream viem@1.0.0 has added the `withRetry` logic as we did here, which I thought would have solved the problem. However, since we're already on viem@1.0.0, it doesn't seem to be doing the trick. Could it be that their number of retries (3) is also not enough?

**Comment by birdgg** [comment]
retryCount has been changed to 6 here https://github.com/wagmi-dev/viem/commit/228d949bce648065ecef629173d1b847e2fc8f21

**Comment by Songkeys** [comment]
We haven't encountered this issue since upgrading to a certain version of `viem`, but I'm not certain. I'm closing this PR for now. If the issue resurfaces in the future, I'll reopen the PR.

**Comment by Songkeys** [comment]
I got the error again in this CI action: https://github.com/Crossbell-Box/crossbell.js/actions/runs/5698179455/job/15445777719

**Pull request merged**
